### PR TITLE
update org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies to 7.0.31

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies` to: `7.0.29`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies 7.0.29

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies 7.0.30

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies 7.0.31

**Comment by ryandawsonuk** [comment]
Will push this change manually

**Pull request closed without merging**
