### PR TITLE
update org.activiti.cloud.modeling:activiti-cloud-org-dependencies to 7.0.11

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.modeling:activiti-cloud-org-dependencies` to: `7.0.9`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.modeling:activiti-cloud-org-dependencies 7.0.9

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.modeling:activiti-cloud-org-dependencies 7.0.10

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.modeling:activiti-cloud-org-dependencies 7.0.11

**Comment by ryandawsonuk** [comment]
Will push this change manually

**Pull request closed without merging**
