### PR TITLE
fix(versions): update Activiti/activiti-cloud-dependencies versions

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies` to: `7.1.11`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies 7.1.11

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.8

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.app:activiti-cloud-app-dependencies 7.1.5

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.audit:activiti-cloud-audit-dependencies 7.1.4

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.connector:activiti-cloud-connectors-dependencies 7.1.6

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.query:activiti-cloud-query-dependencies 7.1.6

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.1.7

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies 7.1.7

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.0.54

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.0.87

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.query:activiti-cloud-query-dependencies 7.0.107

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.rb:activiti-cloud-runtime-bundle-dependencies 7.0.129

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.0.55

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies 7.1.12

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies 7.1.13

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.0.88

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.audit:activiti-cloud-audit-dependencies 7.1.5

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.query:activiti-cloud-query-dependencies 7.0.108

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.common:activiti-cloud-service-common-dependencies 7.1.8

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies 7.1.14

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.query:activiti-cloud-query-dependencies 7.1.7

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.audit:activiti-cloud-audit-dependencies 7.1.6

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.app:activiti-cloud-app-dependencies 7.1.6

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.connector:activiti-cloud-connectors-dependencies 7.0.75

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.app:activiti-cloud-app-dependencies 7.0.65

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.acc:activiti-cloud-acceptance-tests-dependencies 7.0.63

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.audit:activiti-cloud-audit-dependencies 7.0.82

**Comment by ryandawsonuk** [comment]
Not running 7.0.x for now

**Pull request closed without merging**
